---

- name: python3_virtualenv
  src: https://github.com/pwalczysko/ansible-role-python3-virtualenv
  version: try-no-symlink

# - src: ome.omero_server
- name: omero_server
  src: https://github.com/pwalczysko/ansible-role-omero-server
  version: 6.1.0
